In [2]:
import numpy as np 
import math 
import sklearn.metrics 
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0001 ): 
 Q = Q.T 
 for step in range(steps): 
     for i in range(len(R)): 
        for j in range(len(R[i])): 
           if R[i][j] > 0: 
                eij = R[i][j] - np.dot(P[i,:],Q[:,j]) 
                for k in range(K): 
                    P[i][k] = P[i][k] + alpha * 2 * eij * Q[k][j] 
                    Q[k][j] = Q[k][j] + alpha * 2 * eij * P[i][k] 
                    return P, Q.T 
R = [[0,5,4,2, 1],[1,0,0,5, 3], [1,4,4,1, 0],[0,0,2, 0, 2],[3,1,1,0, 0] ] 
R = np.array(R) 
N = len(R) 
# M: num of Movie 
M = len(R[0]) 
# Num of Features 
K = 1 
P = np.random.rand(N,K) 
Q = np.random.rand(M,K) 
nP, nQ = matrix_factorization(R, P, Q, K) 
nR = np.dot(nP, nQ.T)
print("NAME: R U SUGIRDHA")
print("CB.SC.I5DAS21062")
print(nR) 

NAME: R U SUGIRDHA
CB.SC.I5DAS21062
[[0.2450541  0.64599528 0.93371902 0.11845816 0.49074122]
 [0.09485631 0.2500539  0.36142691 0.04585316 0.18995766]
 [0.1347661  0.35526142 0.51349345 0.06514539 0.26988034]
 [0.10578564 0.27886505 0.40307043 0.05113635 0.21184454]
 [0.22092974 0.58240025 0.84179901 0.10679654 0.44243018]]
